### ISSUE TITLE
how to dynamically name for each function

### ISSUE THREAD

**Issue by sgraham785** [digikare/nestjs-prom#10]
this work well thanks. however, I have a service that has multiple functions and I would like to split and track each separately. the easiest way is to name the stat with the function, even append the name when it's invoked in the function? just starting the conversation cause I am not completely clear on how you implemented yet

**Comment by spike008t** [comment]
Hi! Thank you for your feedback.

I don't really understand what you want. Do you mean that you want to create the entry on the fly?

**Comment by sgraham785** [comment]
on the call of a single function in a service. for example is i have a service that has multiple functions that all compose the module. how can i define the entry specific to the function without having to create a separate static configuration for each function in the module and inject in the service

**Comment by sgraham785** [comment]
does my above comment make it clearer? or still need further comments?

**Comment by spike008t** [comment]
Sorry for the delay, I was a quite busy at the moment.

I do understand your need, I'll try to find out some time to handle it. I need to think how can I manage it. I think it can be possible to have something like this:

```typescript
class MyClass {
  @PromCounterMetric('myCounter')
  doStuff() {
    myCounter.inc();
  }
}
```

Or if the aim is to monitor how many time a function is called, can be cool to have something like that:
```typescript
class MyClass {
  @PromCounterMetricAutoInc()
  doStuff() {
  }
}
```

**Comment by spike008t** [comment]
@sgraham785 I've updated the module with new decorators `@PromInstanceCounter` and `@PromMethodCounter`.

It's a simple decorator that will generate automatically counter without need to declare the counter.
See 
- v0.1.0 for nestjs 5
- v0.2.0 for nestjs 6
