### ISSUE TITLE
Great module! Still maintained ?

### ISSUE THREAD

**Issue by appsolutegeek** [digikare/nestjs-prom#12]
Hey, great module.

Are you still maintaining this ?

**Comment by spike008t** [comment]
Hello, thanks. I do not have time to maintaining this module at the moment. But feel free to contribute :)

**Comment by appsolutegeek** [comment]
Ok, thanks. It currently does what I need but hopefully I can extend it in the future or maybe be brought into nestjs itself. Its a great start anyway and currently performs what I need. Thanks
