### ISSUE TITLE
Option "customUrl" is not working for npm package @digikare/nestjs-prom@0.2.1

### ISSUE THREAD

**Issue by p0vidl0** [digikare/nestjs-prom#17]
Distributed to NPM code v.0.2.1 ([archive](https://registry.npmjs.org/@digikare/nestjs-prom/-/nestjs-prom-0.2.1.tgz)) doesn't include this [changes](https://github.com/digikare/nestjs-prom/commit/3d8dbb0f2f662d0acc8e6b11b2eb0ec8f60c208f#diff-ec33e2a92c0070f31282dd76db5932adR36).

![2019-10-10_11-28-33](https://user-images.githubusercontent.com/6966538/66541455-26f54f80-eb51-11e9-9fcd-08aee7e9b826.png)

**Comment by spike008t** [comment]
Thats weird... BTW could you update with `v0.2.2`? I've checked, and customUrl works.

**Comment by spike008t** [comment]
Can I close the issue?

**Comment by spike008t** [comment]
I close the issue. Feel free to re-open a new issue if that issue is still present.
