### ISSUE TITLE
How to access the register

### ISSUE THREAD

**Issue by ab320012** [digikare/nestjs-prom#21]
hey so i am having an issue where HMR is re-registering metrics after a request to the server. From the documentation and cursory look through the source I haven't been able to figure out how to access the register 

here is the open github issue i am trying to solve:

https://github.com/siimon/prom-client/issues/196

if you guys let me know i can pr the docs, thank you.

**Comment by spike008t** [comment]
Actually, as default, the library use the default registry given by prom-client.
But I think that I can manage HMR directly.

**Comment by spike008t** [comment]
v0.2.4 released to support HMR.
Let me know if all works or not

**Comment by ab320012** [comment]
thats perfect
