### ISSUE TITLE
bump to nest version 7.x

### ISSUE THREAD

**Issue by darrenjennings** [digikare/nestjs-prom#26]
Nestjs 7.x versions are out, need to bump nestjs-prom to use latest peerDeps of 7.x.x versions

https://docs.nestjs.com/migration-guide

**Comment by spike008t** [comment]
Sorry for the delay.

The version 1.0.0 will be ready soon and compatible with nestjs v6.x and v7.x.
I'm actually working on it.
Keep in touch

**Comment by spike008t** [comment]
The release v1.0.0 is available on npm!
