### ISSUE TITLE
defaultLabels does not work

### ISSUE THREAD

**Issue by elaijuh** [digikare/nestjs-prom#29]
I setup `defaultLabels` option in forRoot, but it seems not working.

**Comment by spike008t** [comment]
Yes right, I will fix it.
Thank for your reports

**Comment by brunorib62** [comment]
Hi! Thanks for the fix, ran into the same problem few days ago! Any expected day for this to be released?

**Comment by spike008t** [comment]
v0.2.4 is released! Let me know if all is okay
