### ISSUE TITLE
When is ver 1.X scheduled to be released? 

### ISSUE THREAD

**Issue by royi-frontegg** [digikare/nestjs-prom#38]

**Comment by mcijsouw** [comment]
I'm waiting for v1.0.0 as well. The new changes look great!

**Comment by spike008t** [comment]
It will arrived this week :) keep in touch

**Comment by jasyes** [comment]
We are still waiting =)

**Comment by pavel-luhin** [comment]
Really waiting :)

**Comment by royi-frontegg** [comment]
@spike008t any progress on version 1?

**Comment by purwk** [comment]
@spike008t is there anything I can do to help this version release to npm?

**Comment by spike008t** [comment]
Sorry for the very long delay, I just publish the v1.0.0!

**Comment by purwk** [comment]
@spike008t was it reversed? latest is now 0.2.5

**Comment by spike008t** [comment]
@purwk 
Oh I see, i've pushed hotfix 0.2.5 after the 1.0.0 and forget let's the v1.0.0 as latest.
Thank for the update, just udpated!
